# Generated by Django 4.1 on 2022-11-25 11:47

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pathlib.PureWindowsPath(
                    "C:/maybe_final/3rd_Project/mediafiles"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pathlib.PureWindowsPath(
                    "C:/maybe_final/3rd_Project/mediafiles"
                ),
            ),
        ),
    ]
